before_script:
- psql -c 'create database schoolapp_test;' -U postgres
- rvm --default use 2.2.3
#after_script:
#- bundle exec rake db:setup
language: ruby
rvm:
- 2.2.3
- jruby
- rbx-2
deploy:
  provider: heroku
  api_key:
    secure: Cm0qWSa70CAbTVgv1oIab1aL43X/3iVeShChaiWMsWN9aJCj/NitNGlCFxd+O35H9Ozugkm7qSy4u/4N4tZpKg68fVBjAyxWKr7VSDhV9Fxp9f6KyxvvqwHN1Y/25Ha4vs7sWkz+gs+k9G9PPjxRMiW2CEsDpyi+Ab9XhY+9coiJX44ivLh88TWgWftHX/TQ+BnnrpH1HJN1gJw2VkN5pvVT0qqgCH+WaRBtkLLOFlPwRr5XHDpyOjjElsj1AQIlEk1tbCKIz1jIRH4jM5gikp6ilFlZ9hhbx3c4JxuCKc8YqoxzCHwTAXw6mz9fQqVh/CZtWwSVatqPx9dIUr/uNSI4MZnbxrgXeWvcicO5HwM4szbdfjScPwiV+dV9EJ9nTmGVVnhchjVw0/oWbYwjVGSzSghEKIkVNJ6OJrovPu68Tjeu36qMT39haoB6cuYO8/m4OPg7bHbq/yMhZGryD9ArAPtcQSOAgylNV14UkR5lyLKSSF6PssyOIl/Y1bQ+4SfodQ+D691T8oATcjA/w0gXVUN/J2T7Kab4deiaUYoMH6o4EBOZrdOCW+7Gy7S67pOc+8AiLL2jT7xWqjKQMi/5F0UA0/iSPk+ghWZNrmuZxhRJTpADoq1F5OV8xhKMXYSM+wbbfRwdFUOAkKqrD2RzCD1VLuMjFnY90GcrVZM=
  app: polar-woodland-21870
  on:
    repo: rbuchowski1990/school_app
  run: "rake db:setup"
