connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: postgres
  password: password

development:
  <<: *connection
  database: schoolapp_development

test: &test
  <<: *connection
  database: schoolapp_test
